title: Cow Tools
url: "https://cow-tools.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./favicon.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "about"
 - name: "contact"
   link: "contact"
